#! usr/bin/bash

show_help() {
    echo "bashdb is a database engine written in bash. "
    echo "When you first start bashdb you have a main database"
    echo ""
    echo "----------"
    echo "| Prompt |"
    echo "----------"
    printf "  %-20s%s\n" "\"bashdb@# >\"" " # means you are currently not connected to any database"
    printf "  %-20s%s\n" "\"bashdb@NAME >\"" "NAME is the name of the databases you are currently connected to."
    echo ""
    echo "------------"
    echo "| Commands |"
    echo "------------"
    printf "  %-20s%s\n" "help" "Shows this help"
    printf "  %-20s%s\n" "clear" "Clears the terminal"
    echo ""

    echo "  not connected to a database"
    printf "  %-20s%s\n" "ls" "Lists all existing databases"
    printf "  %-20s%s\n" "exit" "Exits from bashdb"
    printf "  %-20s%s\n" "drop NAME" "Deletes a database"
    printf "  %-20s%s\n" "create NAME" "Creates a new database"
    printf "  %-20s%s\n" "connect NAME" "Connects to a database"
    echo " "
    echo "  connected to a database"
    printf "  %-20s%s\n" "ls" "Lists all existing tables"
    printf "  %-20s%s\n" "exit" "Exits from connected database"
    echo " "
    echo "------------------"
    echo "| Queries syntax |"
    echo "------------------"
    printf "  %-20s%s\n" "Create" "create table TABLE_NAME (COLUMN_NAME TYPE [PRIMARY KEY] , ...)"
    printf "  %-20s%s\n" "Drop" "drop table TABLE_NAME"
    printf "  %-20s%s\n" "Insert" "insert into TABLE_NAME (COLUMN_NAME, ...) values (VALUE, ...)"
    printf "  %-20s%s\n" "Select" "select (COLUMN_NAME, ...) from TABLE_NAME where CONDITION"
    printf "  %-20s%s\n" "Update" "update TABLE_NAME set (COLUMN_NAME = VALUE, ...) where CONDITION"
    printf "  %-20s%s\n" "Delete" "delete from TABLE_NAME where CONDITION"
    echo " "
    echo "---------"
    echo "| Hints |"
    echo "---------"

    echo "  - Names in bashdb have to start with a character followed by any number of characters, digits or underscores."
    echo "  - where clause only supports one condition."
    echo "  - supported types are (int or varchar)."
    echo "  - supported constraint : primary key."
    echo "  - supported logical operators for int are (>, <, >=, <=, =, !=)."
    echo "  - supported logical operators for varchar are (=, !=)."

}
